/* eslint-disable camelcase */
export interface IData {
  data: string
  confirmados: string
  recuperados: string
  obitos: string
  internados: string
  lab: string
  suspeitos: string
  vigilancia: string
  ativos: string
  dataDados: string
  confirmadosArsnorte: string
  confirmadosArscentro: string
  confirmadosArslvt: string
  confirmadosArsalentejo: string
  confirmadosArsalgarve: string
  confirmadosAcores: string
  confirmadosMadeira: string
  confirmadosEstrangeiro: string
  confirmadosNovos: string
  internadosUci: string
  nConfirmados: string
  cadeiasTransmissao: string
  transmissaoImportada: string
  confirmados_0_9F: string
  confirmados_0_9M: string
  confirmados_10_19F: string
  confirmados_10_19M: string
  confirmados_20_29F: string
  confirmados_20_29M: string
  confirmados_30_39F: string
  confirmados_30_39M: string
  confirmados_40_49F: string
  confirmados_40_49M: string
  confirmados_50_59F: string
  confirmados_50_59M: string
  confirmados_60_69F: string
  confirmados_60_69M: string
  confirmados_70_79F: string
  confirmados_70_79M: string
  confirmados_80PlusF: string
  confirmados_80PlusM: string
  sintomasTosse: string
  sintomasFebre: string
  sintomasDificuldadeRespiratoria: string
  sintomasCefaleia: string
  sintomasDoresMusculares: string
  sintomasFraquezaGeneralizada: string
  confirmadosF: string
  confirmadosM: string
  obitosArsnorte: string
  obitosArscentro: string
  obitosArslvt: string
  obitosArsalentejo: string
  obitosArsalgarve: string
  obitosAcores: string
  obitosMadeira: string
  obitosEstrangeiro: string
  recuperadosArsnorte: string
  recuperadosArscentro: string
  recuperadosArslvt: string
  recuperadosArsalentejo: string
  recuperadosArsalgarve: string
  recuperadosAcores: string
  recuperadosMadeira: string
  recuperadosEstrangeiro: string
  obitos_0_9F: string
  obitos_0_9M: string
  obitos_10_19F: string
  obitos_10_19M: string
  obitos_20_29F: string
  obitos_20_29M: string
  obitos_30_39F: string
  obitos_30_39M: string
  obitos_40_49F: string
  obitos_40_49M: string
  obitos_50_59F: string
  obitos_50_59M: string
  obitos_60_69F: string
  obitos_60_69M: string
  obitos_70_79F: string
  obitos_70_79M: string
  obitos_80PlusF: string
  obitos_80PlusM: string
  obitosF: string
  obitosM: string
  confirmadosDesconhecidosM: string
  confirmadosDesconhecidosF: string
  internadosEnfermaria: string
  confirmadosDesconhecidos: string
  incidenciaNacional: string
  incidenciaContinente: string
  rtNacional: string
  rtContinente: string
}

export interface IDataUpdate {
  confirmados: number
  recuperados: number
  obitos: number
  internados: number
  lab: number
  suspeitos: number
  vigilancia: number
  ativos: number
  confirmadosArsnorte: number
  confirmadosArscentro: number
  confirmadosArslvt: number
  confirmadosArsalentejo: number
  confirmadosArsalgarve: number
  confirmadosAcores: number
  confirmadosMadeira: number
  confirmadosEstrangeiro: number
  confirmadosNovos: number
  internadosUci: number
  nConfirmados: number
  cadeiasTransmissao: number
  transmissaoImportada: number
  confirmados_0_9F: number
  confirmados_0_9M: number
  confirmados_10_19F: number
  confirmados_10_19M: number
  confirmados_20_29F: number
  confirmados_20_29M: number
  confirmados_30_39F: number
  confirmados_30_39M: number
  confirmados_40_49F: number
  confirmados_40_49M: number
  confirmados_50_59F: number
  confirmados_50_59M: number
  confirmados_60_69F: number
  confirmados_60_69M: number
  confirmados_70_79F: number
  confirmados_70_79M: number
  confirmados_80PlusF: number
  confirmados_80PlusM: number
  sintomasTosse: number
  sintomasFebre: number
  sintomasDificuldadeRespiratoria: number
  sintomasCefaleia: number
  sintomasDoresMusculares: number
  sintomasFraquezaGeneralizada: number
  confirmadosF: number
  confirmadosM: number
  obitosArsnorte: number
  obitosArscentro: number
  obitosArslvt: number
  obitosArsalentejo: number
  obitosArsalgarve: number
  obitosAcores: number
  obitosMadeira: number
  obitosEstrangeiro: number
  recuperadosArsnorte: number
  recuperadosArscentro: number
  recuperadosArslvt: number
  recuperadosArsalentejo: number
  recuperadosArsalgarve: number
  recuperadosAcores: number
  recuperadosMadeira: number
  recuperadosEstrangeiro: number
  obitos_0_9F: number
  obitos_0_9M: number
  obitos_10_19F: number
  obitos_10_19M: number
  obitos_20_29F: number
  obitos_20_29M: number
  obitos_30_39F: number
  obitos_30_39M: number
  obitos_40_49F: number
  obitos_40_49M: number
  obitos_50_59F: number
  obitos_50_59M: number
  obitos_60_69F: number
  obitos_60_69M: number
  obitos_70_79F: number
  obitos_70_79M: number
  obitos_80PlusF: number
  obitos_80PlusM: number
  obitosF: number
  obitosM: number
  confirmadosDesconhecidosM: number
  confirmadosDesconhecidosF: number
  internadosEnfermaria: number
  confirmadosDesconhecidos: number
  incidenciaNacional: number
  incidenciaContinente: number
  rtNacional: number
  rtContinente: number
  data: string
}
